<?php
session_start();
?>

<!DOCTYPE html>
<html>

<head>
    <title>Play Pairs</title>
    <link rel="stylesheet" href="css/style.css">
    <script src="js/game.js" defer></script>
</head>

<body>

    <div id="navbar">

        <a name="home" href="index.php">Home</a>

        <div class="right">

            <a name="memory" href="pairs.php">Play Pairs</a>

            <?php
            if (isset($_SESSION['username'])) {
                echo '<a name="leaderboard" href="leaderboard.php">Leaderboard</a>';
            } else {
                echo '<a name="register" href="registration.php">Register</a>';
            }
            ?>

            <?php
            if (isset($_COOKIE['avatar'])) {
                echo "<span style='margin-left:10px;'>" . $_COOKIE['avatar'] . "</span>";
            }
            ?>

        </div>
    </div>


    <div id="main">

        <div id="game-container">

            <h2>Memory Game</h2>

            <button id="startBtn">Start the game</button>

        <div id="game-info">
            <p>Level: <span id="levelDisplay">1</span></p>
            <p>Attempts: <span id="attempts">0</span></p>
            <p>Time: <span id="timer">0</span></p>
            <p>Score: <span id="score">0</span></p>

        </div>

            <div id="game-board">

                <!-- cards will be generated by JS -->

            </div>
            <div id="game-controls" style="display:none;">
                <form method="POST" action="leaderboard.php">
                    <input type="hidden" name="score" id="finalScore">
                    <button type="submit">Submit Score</button>
                </form>

                <button onclick="restartGame()">Play Again</button>
            </div>

        </div>

    </div>

</body>

</html>