<?php
// Start the session to check if the user is registered and display correct navbar links
session_start();
?>

<!DOCTYPE html>
<html>

<head>
    <title>Play Pairs</title>
    <!-- Link to shared stylesheet for consistent layout across all pages -->
    <link rel="stylesheet" href="css/style.css">
    <!-- Load game logic — deferred so it runs after the DOM is fully loaded -->
    <script src="js/game.js" defer></script>
</head>

<body>

    <div id="navbar">

        <!-- Home link aligned to the left of the navbar -->
        <a name="home" href="index.php">Home</a>

        <div class="right">

            <!-- Play Pairs link always visible in the navbar -->
            <a name="memory" href="pairs.php">Play Pairs</a>

            <?php
            // Show Leaderboard link for registered users, Register link for guests
            if (isset($_SESSION['username'])) {
                echo '<a name="leaderboard" href="leaderboard.php">Leaderboard</a>';
            } else {
                echo '<a name="register" href="registration.php">Register</a>';
            }
            ?>

            <?php
            // Display the user's avatar emoji in the navbar if one has been set
            if (isset($_COOKIE['avatar'])) {
                echo "<span style='margin-left:10px;'>" . $_COOKIE['avatar'] . "</span>";
            }
            ?>

        </div>
    </div>


    <div id="main">

        <!-- Game container with grey background and box shadow as per specification -->
        <div id="game-container">

            <h2>Memory Game</h2>

            <!-- Start button — hidden by JS once the game begins -->
            <button id="startBtn">Start the game</button>

            <!-- Live game stats displayed during gameplay -->
            <div id="game-info">
                <p>Level: <span id="levelDisplay">1</span></p>
                <p>Attempts: <span id="attempts">0</span></p>
                <p>Time: <span id="timer">0</span></p>
                <p>Score: <span id="score">0</span></p>
            </div>

            <!-- Game board — card elements are dynamically generated by game.js -->
            <div id="game-board">
                <!-- cards will be generated by JS -->
            </div>

            <!-- End of game controls — hidden until all levels are complete -->
            <div id="game-controls" style="display:none;">

                <!-- POST form sends the final score to leaderboard.php on submission -->
                <form method="POST" action="leaderboard.php">
                    <!-- Hidden input populated by JS with the final total score -->
                    <input type="hidden" name="score" id="finalScore">
                    <button type="submit">Submit Score</button>
                </form>

                <!-- Reloads the page to restart the game and reset all state -->
                <button onclick="restartGame()">Play Again</button>

            </div>

        </div>

    </div>

</body>

</html>